import type { Locale } from "./config";

export interface CookieCopy {
  title: string;
  intro: string;
  policy: string;
  accept: string;
  reject: string;
  configure: string;
  save: string;
  settings: string;
  close: string;
  alwaysOn: string;
  categories: {
    necessary: { title: string; body: string };
    analytics: { title: string; body: string };
    maps: { title: string; body: string };
    marketing: { title: string; body: string };
  };
}

export const cookieDictionaries: Record<Locale, CookieCopy> = {
  es: { title: "Tu privacidad, bajo tu control", intro: "Usamos almacenamiento técnico para que la web funcione. Las analíticas, los mapas externos y el marketing permanecen desactivados hasta que los autorices.", policy: "Política de cookies", accept: "Aceptar opcionales", reject: "Rechazar opcionales", configure: "Configurar", save: "Guardar preferencias", settings: "Preferencias de cookies", close: "Cerrar", alwaysOn: "Siempre activas", categories: { necessary: { title: "Técnicas", body: "Sesión, seguridad, idioma y preferencias imprescindibles." }, analytics: { title: "Analíticas", body: "Métricas agregadas para mejorar el servicio." }, maps: { title: "Mapas externos", body: "Contenido y servicios cartográficos de terceros." }, marketing: { title: "Marketing", body: "Medición de campañas y comunicaciones personalizadas." } } },
  fr: { title: "Votre vie privée, sous votre contrôle", intro: "Nous utilisons le stockage technique pour faire fonctionner le site. Les statistiques, cartes externes et outils marketing restent désactivés sans votre accord.", policy: "Politique relative aux cookies", accept: "Accepter les options", reject: "Refuser les options", configure: "Configurer", save: "Enregistrer les préférences", settings: "Préférences de cookies", close: "Fermer", alwaysOn: "Toujours actifs", categories: { necessary: { title: "Techniques", body: "Session, sécurité, langue et préférences indispensables." }, analytics: { title: "Statistiques", body: "Mesures agrégées pour améliorer le service." }, maps: { title: "Cartes externes", body: "Contenus et services cartographiques tiers." }, marketing: { title: "Marketing", body: "Mesure des campagnes et communications personnalisées." } } },
  it: { title: "La tua privacy, sotto il tuo controllo", intro: "Usiamo l’archiviazione tecnica per il funzionamento del sito. Analisi, mappe esterne e marketing restano disattivati senza il tuo consenso.", policy: "Informativa sui cookie", accept: "Accetta opzionali", reject: "Rifiuta opzionali", configure: "Configura", save: "Salva preferenze", settings: "Preferenze cookie", close: "Chiudi", alwaysOn: "Sempre attivi", categories: { necessary: { title: "Tecnici", body: "Sessione, sicurezza, lingua e preferenze indispensabili." }, analytics: { title: "Analitici", body: "Metriche aggregate per migliorare il servizio." }, maps: { title: "Mappe esterne", body: "Contenuti e servizi cartografici di terze parti." }, marketing: { title: "Marketing", body: "Misurazione delle campagne e comunicazioni personalizzate." } } },
  pt: { title: "A sua privacidade, sob o seu controlo", intro: "Utilizamos armazenamento técnico para o funcionamento do site. As análises, mapas externos e marketing ficam desativados sem o seu consentimento.", policy: "Política de cookies", accept: "Aceitar opcionais", reject: "Rejeitar opcionais", configure: "Configurar", save: "Guardar preferências", settings: "Preferências de cookies", close: "Fechar", alwaysOn: "Sempre ativas", categories: { necessary: { title: "Técnicas", body: "Sessão, segurança, idioma e preferências essenciais." }, analytics: { title: "Analíticas", body: "Métricas agregadas para melhorar o serviço." }, maps: { title: "Mapas externos", body: "Conteúdos e serviços cartográficos de terceiros." }, marketing: { title: "Marketing", body: "Medição de campanhas e comunicações personalizadas." } } },
  de: { title: "Ihre Privatsphäre, Ihre Entscheidung", intro: "Technische Speicherung ist für den Betrieb der Website erforderlich. Analyse, externe Karten und Marketing bleiben ohne Ihre Zustimmung deaktiviert.", policy: "Cookie-Richtlinie", accept: "Optionale akzeptieren", reject: "Optionale ablehnen", configure: "Konfigurieren", save: "Einstellungen speichern", settings: "Cookie-Einstellungen", close: "Schließen", alwaysOn: "Immer aktiv", categories: { necessary: { title: "Technisch", body: "Sitzung, Sicherheit, Sprache und notwendige Einstellungen." }, analytics: { title: "Analyse", body: "Zusammengefasste Messwerte zur Verbesserung des Dienstes." }, maps: { title: "Externe Karten", body: "Karteninhalte und Dienste von Drittanbietern." }, marketing: { title: "Marketing", body: "Kampagnenmessung und personalisierte Kommunikation." } } },
  nl: { title: "Jouw privacy, jouw keuze", intro: "Technische opslag is nodig om de website te laten werken. Analyse, externe kaarten en marketing blijven zonder toestemming uitgeschakeld.", policy: "Cookiebeleid", accept: "Optionele accepteren", reject: "Optionele weigeren", configure: "Instellen", save: "Voorkeuren opslaan", settings: "Cookievoorkeuren", close: "Sluiten", alwaysOn: "Altijd actief", categories: { necessary: { title: "Technisch", body: "Sessie, beveiliging, taal en noodzakelijke voorkeuren." }, analytics: { title: "Analyse", body: "Geaggregeerde metingen om de dienst te verbeteren." }, maps: { title: "Externe kaarten", body: "Kaartinhoud en diensten van derden." }, marketing: { title: "Marketing", body: "Campagnemeting en gepersonaliseerde communicatie." } } },
  en: { title: "Your privacy, under your control", intro: "We use technical storage to keep the website working. Analytics, external maps and marketing stay disabled until you allow them.", policy: "Cookie policy", accept: "Accept optional", reject: "Reject optional", configure: "Configure", save: "Save preferences", settings: "Cookie preferences", close: "Close", alwaysOn: "Always on", categories: { necessary: { title: "Technical", body: "Session, security, language and essential preferences." }, analytics: { title: "Analytics", body: "Aggregated measurements used to improve the service." }, maps: { title: "External maps", body: "Third-party mapping content and services." }, marketing: { title: "Marketing", body: "Campaign measurement and personalised communications." } } },
};
