import type { Locale } from "./config";

export interface DashboardCopy {
  account: string;
  backToSite: string;
  closeMenu: string;
  loading: string;
  logout: string;
  navigation: string;
  openMenu: string;
  changeMode: string;
  roles: Record<"client" | "professional" | "company" | "subcontractor", string>;
  modeLabels: Record<"client" | "professional" | "company" | "subcontractor", string>;
  nav: Record<"overview" | "subscription" | "requests" | "opportunities" | "balance" | "preferences" | "profile" | "services" | "reviews" | "tools" | "clientProjects" | "findProfessionals" | "guide", string>;
  onboarding: Record<"eyebrow" | "title" | "subtitle" | "hide" | "note" | "clientProject" | "clientDetails" | "clientSearch" | "clientFavorites" | "clientCompare" | "proProfile" | "proServices" | "proPreferences" | "proWorks" | "proQuote" | "companyData" | "companySpecialties" | "companyRequests" | "companyTeam" | "companyDocs", string>;
}

export const dashboardDictionaries: Record<Locale, DashboardCopy> = {
  es: { account: "Cuenta", backToSite: "Volver a la web", closeMenu: "Cerrar menú", loading: "Comprobando tu sesión...", logout: "Cerrar sesión", navigation: "Navegación del panel", openMenu: "Abrir menú", changeMode: "Cambiar modo", roles: { client: "Cliente", professional: "Profesional", company: "Empresa", subcontractor: "Subcontrata" }, modeLabels: { client: "Modo cliente", professional: "Modo profesional", company: "Modo empresa", subcontractor: "Modo subcontrata" }, nav: { overview: "Resumen", subscription: "Suscripción", requests: "Solicitudes", opportunities: "Oportunidades", balance: "Saldo", preferences: "Preferencias", profile: "Mi perfil", services: "Mis servicios", reviews: "Valoraciones", tools: "Herramientas", clientProjects: "Mis proyectos", findProfessionals: "Buscar profesionales", guide: "Guía y ayuda" }, onboarding: { eyebrow: "Primeros pasos", title: "Completa tu configuración en orden", subtitle: "Sigue estos pasos para sacar valor de RegiKaha sin perderte dentro del panel.", hide: "Ocultar primeros pasos", note: "Puedes ocultar este bloque y volver a usar el menú cuando ya controles el flujo.", clientProject: "Publica tu primer proyecto", clientDetails: "Añade ciudad, fotos y detalles", clientSearch: "Busca profesionales", clientFavorites: "Guarda favoritos", clientCompare: "Compara respuestas", proProfile: "Completa tu perfil", proServices: "Añade servicios", proPreferences: "Define zonas y preferencias", proWorks: "Abre Regi Works", proQuote: "Crea tu primer presupuesto", companyData: "Completa datos de empresa", companySpecialties: "Añade especialidades", companyRequests: "Gestiona solicitudes", companyTeam: "Organiza equipo", companyDocs: "Genera documentos" } },
  fr: { account: "Compte", backToSite: "Retour au site", closeMenu: "Fermer le menu", loading: "Vérification de votre session...", logout: "Se déconnecter", navigation: "Navigation du tableau de bord", openMenu: "Ouvrir le menu", changeMode: "Changer de mode", roles: { client: "Client", professional: "Professionnel", company: "Entreprise", subcontractor: "Sous-traitant" }, modeLabels: { client: "Mode client", professional: "Mode professionnel", company: "Mode entreprise", subcontractor: "Mode sous-traitant" }, nav: { overview: "Vue d'ensemble", subscription: "Abonnement", requests: "Demandes", opportunities: "Opportunités", balance: "Solde", preferences: "Préférences", profile: "Mon profil", services: "Mes services", reviews: "Avis", tools: "Outils", clientProjects: "Mes projets", findProfessionals: "Trouver des pros", guide: "Guide et aide" }, onboarding: { eyebrow: "Premiers pas", title: "Configurez votre espace dans l'ordre", subtitle: "Suivez ces étapes pour tirer de la valeur de RegiKaha sans vous perdre dans le tableau de bord.", hide: "Masquer les premiers pas", note: "Vous pouvez masquer ce bloc lorsque vous maîtrisez le flux.", clientProject: "Publier votre premier projet", clientDetails: "Ajouter ville, photos et détails", clientSearch: "Trouver des professionnels", clientFavorites: "Enregistrer des favoris", clientCompare: "Comparer les réponses", proProfile: "Compléter votre profil", proServices: "Ajouter vos services", proPreferences: "Définir zones et préférences", proWorks: "Ouvrir Regi Works", proQuote: "Créer votre premier devis", companyData: "Compléter les données société", companySpecialties: "Ajouter les spécialités", companyRequests: "Gérer les demandes", companyTeam: "Organiser l'équipe", companyDocs: "Générer des documents" } },
  it: { account: "Account", backToSite: "Torna al sito", closeMenu: "Chiudi menu", loading: "Verifica della sessione...", logout: "Esci", navigation: "Navigazione del pannello", openMenu: "Apri menu", changeMode: "Cambia modalità", roles: { client: "Cliente", professional: "Professionista", company: "Azienda", subcontractor: "Subappaltatore" }, modeLabels: { client: "Modalità cliente", professional: "Modalità professionista", company: "Modalità azienda", subcontractor: "Modalità subappalto" }, nav: { overview: "Riepilogo", subscription: "Abbonamento", requests: "Richieste", opportunities: "Opportunità", balance: "Saldo", preferences: "Preferenze", profile: "Il mio profilo", services: "I miei servizi", reviews: "Recensioni", tools: "Strumenti", clientProjects: "I miei progetti", findProfessionals: "Trova professionisti", guide: "Guida e aiuto" }, onboarding: { eyebrow: "Primi passi", title: "Configura il tuo spazio in ordine", subtitle: "Segui questi passaggi per ottenere valore da RegiKaha senza perderti nel pannello.", hide: "Nascondi primi passi", note: "Puoi nascondere questo blocco quando conosci il flusso.", clientProject: "Pubblica il primo progetto", clientDetails: "Aggiungi città, foto e dettagli", clientSearch: "Trova professionisti", clientFavorites: "Salva preferiti", clientCompare: "Confronta risposte", proProfile: "Completa il profilo", proServices: "Aggiungi servizi", proPreferences: "Definisci zone e preferenze", proWorks: "Apri Regi Works", proQuote: "Crea il primo preventivo", companyData: "Completa dati azienda", companySpecialties: "Aggiungi specialità", companyRequests: "Gestisci richieste", companyTeam: "Organizza il team", companyDocs: "Genera documenti" } },
  pt: { account: "Conta", backToSite: "Voltar ao site", closeMenu: "Fechar menu", loading: "A verificar a sua sessão...", logout: "Terminar sessão", navigation: "Navegação do painel", openMenu: "Abrir menu", changeMode: "Mudar modo", roles: { client: "Cliente", professional: "Profissional", company: "Empresa", subcontractor: "Subcontratado" }, modeLabels: { client: "Modo cliente", professional: "Modo profissional", company: "Modo empresa", subcontractor: "Modo subcontratado" }, nav: { overview: "Resumo", subscription: "Subscrição", requests: "Pedidos", opportunities: "Oportunidades", balance: "Saldo", preferences: "Preferências", profile: "O meu perfil", services: "Os meus serviços", reviews: "Avaliações", tools: "Ferramentas", clientProjects: "Os meus projetos", findProfessionals: "Encontrar profissionais", guide: "Guia e ajuda" }, onboarding: { eyebrow: "Primeiros passos", title: "Complete a configuração por ordem", subtitle: "Siga estes passos para tirar valor do RegiKaha sem se perder no painel.", hide: "Ocultar primeiros passos", note: "Pode ocultar este bloco quando já dominar o fluxo.", clientProject: "Publique o primeiro projeto", clientDetails: "Adicione cidade, fotos e detalhes", clientSearch: "Encontre profissionais", clientFavorites: "Guarde favoritos", clientCompare: "Compare respostas", proProfile: "Complete o perfil", proServices: "Adicione serviços", proPreferences: "Defina zonas e preferências", proWorks: "Abra Regi Works", proQuote: "Crie o primeiro orçamento", companyData: "Complete dados da empresa", companySpecialties: "Adicione especialidades", companyRequests: "Gerir pedidos", companyTeam: "Organizar equipa", companyDocs: "Gerar documentos" } },
  de: { account: "Konto", backToSite: "Zur Website", closeMenu: "Menü schließen", loading: "Sitzung wird geprüft...", logout: "Abmelden", navigation: "Dashboard-Navigation", openMenu: "Menü öffnen", changeMode: "Modus wechseln", roles: { client: "Kunde", professional: "Fachbetrieb", company: "Unternehmen", subcontractor: "Subunternehmer" }, modeLabels: { client: "Kundenmodus", professional: "Profi-Modus", company: "Unternehmensmodus", subcontractor: "Subunternehmermodus" }, nav: { overview: "Übersicht", subscription: "Abonnement", requests: "Anfragen", opportunities: "Aufträge", balance: "Guthaben", preferences: "Einstellungen", profile: "Mein Profil", services: "Meine Leistungen", reviews: "Bewertungen", tools: "Werkzeuge", clientProjects: "Meine Projekte", findProfessionals: "Fachleute finden", guide: "Hilfe & Anleitung" }, onboarding: { eyebrow: "Erste Schritte", title: "Richten Sie alles der Reihe nach ein", subtitle: "Folgen Sie diesen Schritten, um RegiKaha ohne Umwege sinnvoll zu nutzen.", hide: "Erste Schritte ausblenden", note: "Sie können diesen Block ausblenden, sobald Sie den Ablauf kennen.", clientProject: "Erstes Projekt veröffentlichen", clientDetails: "Stadt, Fotos und Details hinzufügen", clientSearch: "Fachleute suchen", clientFavorites: "Favoriten speichern", clientCompare: "Antworten vergleichen", proProfile: "Profil vervollständigen", proServices: "Leistungen hinzufügen", proPreferences: "Gebiete und Präferenzen setzen", proWorks: "Regi Works öffnen", proQuote: "Erstes Angebot erstellen", companyData: "Firmendaten vervollständigen", companySpecialties: "Spezialisierungen hinzufügen", companyRequests: "Anfragen verwalten", companyTeam: "Team organisieren", companyDocs: "Dokumente erzeugen" } },
  nl: { account: "Account", backToSite: "Terug naar de site", closeMenu: "Menu sluiten", loading: "Je sessie wordt gecontroleerd...", logout: "Uitloggen", navigation: "Dashboardnavigatie", openMenu: "Menu openen", changeMode: "Modus wijzigen", roles: { client: "Klant", professional: "Vakman", company: "Bedrijf", subcontractor: "Onderaannemer" }, modeLabels: { client: "Klantmodus", professional: "Vakmodus", company: "Bedrijfsmodus", subcontractor: "Onderaannemermodus" }, nav: { overview: "Overzicht", subscription: "Abonnement", requests: "Aanvragen", opportunities: "Opdrachten", balance: "Saldo", preferences: "Voorkeuren", profile: "Mijn profiel", services: "Mijn diensten", reviews: "Beoordelingen", tools: "Hulpmiddelen", clientProjects: "Mijn projecten", findProfessionals: "Vakmensen zoeken", guide: "Gids en hulp" }, onboarding: { eyebrow: "Eerste stappen", title: "Richt alles stap voor stap in", subtitle: "Volg deze stappen om RegiKaha goed te gebruiken zonder te verdwalen in het dashboard.", hide: "Eerste stappen verbergen", note: "Je kunt dit blok verbergen zodra je de workflow kent.", clientProject: "Plaats je eerste project", clientDetails: "Voeg stad, foto's en details toe", clientSearch: "Zoek vakmensen", clientFavorites: "Sla favorieten op", clientCompare: "Vergelijk reacties", proProfile: "Vul je profiel aan", proServices: "Voeg diensten toe", proPreferences: "Stel regio's en voorkeuren in", proWorks: "Open Regi Works", proQuote: "Maak je eerste offerte", companyData: "Vul bedrijfsgegevens aan", companySpecialties: "Voeg specialisaties toe", companyRequests: "Beheer aanvragen", companyTeam: "Organiseer team", companyDocs: "Genereer documenten" } },
  en: { account: "Account", backToSite: "Back to the website", closeMenu: "Close menu", loading: "Checking your session...", logout: "Sign out", navigation: "Dashboard navigation", openMenu: "Open menu", changeMode: "Switch mode", roles: { client: "Client", professional: "Professional", company: "Company", subcontractor: "Subcontractor" }, modeLabels: { client: "Client mode", professional: "Professional mode", company: "Company mode", subcontractor: "Subcontractor mode" }, nav: { overview: "Overview", subscription: "Subscription", requests: "Requests", opportunities: "Opportunities", balance: "Balance", preferences: "Preferences", profile: "My profile", services: "My services", reviews: "Reviews", tools: "Tools", clientProjects: "My projects", findProfessionals: "Find professionals", guide: "Guide and help" }, onboarding: { eyebrow: "First steps", title: "Complete your setup in order", subtitle: "Follow these steps to get value from RegiKaha without getting lost in the dashboard.", hide: "Hide first steps", note: "You can hide this block once you know the workflow.", clientProject: "Publish your first project", clientDetails: "Add city, photos and details", clientSearch: "Find professionals", clientFavorites: "Save favourites", clientCompare: "Compare replies", proProfile: "Complete your profile", proServices: "Add services", proPreferences: "Set areas and preferences", proWorks: "Open Regi Works", proQuote: "Create your first quote", companyData: "Complete company data", companySpecialties: "Add specialties", companyRequests: "Manage requests", companyTeam: "Organise the team", companyDocs: "Generate documents" } },
};
